# ---------------------------------- 数据库 ---------------------------------
db:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.50.168:3306/potato?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Iwhere123$

# ---------------------------------- Mybatis 配置 ---------------------------------
mybatis:
   mapper-locations: ["classpath:org/potato/AnyThing/phoenix/dao/generator/mapping/*Mapper.xml", "classpath:org/potato/AnyThing/phoenix/dao/generator/mapping/*Dao.xml"]

# ---------------------------------- Hbase 配置 ---------------------------------
hbase:
  zkHost: pro1,pro2,pro3
  zkPort: 2181
  table: EP
